### ISSUE TITLE
ID review

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/guide-microprofile-graphql#21]
## What you'll learn
- [x] Change "GraphQL is an open source data query and manipulation language” to “GraphQL is an open source data query language” to be more concise. The reference to “data query” already implies that data is manipulated so you don’t need to explicitly state "manipulation".
- [x] Change "Unlike REST APIs, POST requests going to a GraphQL service all go to a single HTTP endpoint.” to “Unlike REST APIs, each POST request that is sent to a GraphQL service goes to a single HTTP endpoint” to clarify how the request interacts with the service.
- [x] Add a sentence before the sentence that starts with “Operations” to explain to what operations are or clarify what operations you are referring to avoid confusion.
- [x] Typo: Change “data they want returned” to “data that they want returned"
- [x] Add a sentence or phrase before the sentence that starts with “A JSON object” to explain how, why, or when a JSON object is returned. The sentence needs additional context to maintain clarity.
- [x] In the phrase “This is beneficial”, add a noun after “This” to clarify what you are referring to.
- [x] After the phrase, “with large resources or”, change “ones” to “resources” to avoid ambiguity.
- [x] Change “beneficial when dealing” to “beneficial when you deal”
- [x] Typo: Change “reduces time by only calculating them” to “reduces time by calculating them only”
- [x] Typo: Change “The service you’ll create” to “The service that you’ll create”
- [x] Typo: Change “requests made” to “requests that are made”
- [x] Typo: Change “The operations you’ll implement” to “The operations that you’ll implement”
- [x] Typo: Change “the application will be done using GraphiQL” to “the application will be done by using GraphiQL”
- [x] Change " In GraphiQL you only need to type the body of the request, streamlining manual tests.” to "In GraphiQL you need to type only the body of the request, which streamlines manual tests.” to make the meaning of the sentence clearer.
## Getting Started
- [x] Change “input box on the left” to “input box” to avoid potential accessibility violations. 
- [x] Change "Press `CTRL+enter` to run your query operation. The output will appear in the text box on the right, and will be similar to the following:” to something like, “Press `CTRL+enter` to run your query operation and generate output that is similar to the following example:” to avoid potential accessibility violations and avoid future tense.
## Creating GraphQL object types
- [x] Typo: Change “known as dev mode” to “which is known as dev mode”
- [ ] Change “You’ll create” to “You can create” to avoid future tense.
- [x] Change “You’ll apply” to “You can also apply” to avoid future tense.
- [x] Change “object type will give” to “object type gives” to avoid future tense.
- [x] Change “This description is what will appear” to “This description is what appears” to avoid future tense.
- [x] Change “will be automatically mapped” to “is automatically mapped” to avoid future tense.
- [x] Change “will automatically be” to “are automatically” to avoid future tense
## Implementing GraphQL resolvers
- [ ] Change “We’ll implement” to “You can implement” to avoid future tense.
- [x] Change "The `@GraphQLApi` annotation makes it so that GraphQL will use the methods defined in this class as resolvers.” to “The `@GraphQLApi` annotation enables GraphQL to use the methods that are defined in this class as resolvers” to be more concise and avoid future tense.
- [x] Change “Here the `@Query` annotation” to “This annotation” to avoid potential accessibility violations.
- [x] Change “retrieving the system information” to “which retrieves the system information”.
- [x] Change "Here the `@Mutation` annotation” to “This annotation” to avoid potential accessibility violations.
- [x] Change “what inputs will be used” to “what inputs are used” to avoid future tense
- [x] Change "Here, there’s just one input note for the note to write into the system properties.” to something like, “Within the  @Name annotation, the note input specifies the note is written into the system properties” to add more clarity to the meaning of the sentence
- [x] Change "Here the `@Source` annotation” to “This annotation” to avoid potential accessibility violations.
- [x] Change “look up” to “search for” to avoid potential accessibility violations.
- [x] Change "These properties will only be calculated or looked up if requested, saving server time and resources.” to “These properties are calculated or searched for only if requested, which saves time and resources.” to avoid future tense and accessibility violations
## Enabling GraphQL
- [x] Typo: Change “annotations used” to “annotations that are used”
- [x] Typo: Change “feature added” to “feature that is added”
## Running the application
- [x] Change "You started the Open Liberty server in dev mode at the beginning of the guide, so all the changes were automatically picked up.” to “Because you started the Open Liberty server in dev mode, the changes that you made were automatically picked up.” to be more concise. 
- [x] Change “will be the same” to “are the same” to avoid future tense
- [x] Change “will describes” to “describes” to avoid future tense
- [x] Change "The schema gives details on the various operations available and descriptions of them” to “The schema gives details on the various operations that are available” to be more concise since descriptions are details.
- [x] Change “you’ll also be able to see” to “you can also see” to avoid future tense.
- [x] Typo: Change “fields contained” to “fields that are contained”
- [x] Change “will also be visible” to “is also visible”
- [x] Change "Run the following `query` operation to get every system property by entering it into GraphiQL.” to “Run the following `query` operation in GraphiQL to get every system property” to be more concise.
- [x] Typo: Change “similar to the following” to “similar to the following example” 
- [x] Typo: Change “You’ll receive” to “You receive” to avoid future tense
- [x] Typo: Change “note you added” to “note that you added”
- [x] Change “The response will be similar to the following” to “The response is similar to the following example” to avoid future tense and fix a typo.
- [x] Change “Notice that this time, only the note property” to “Notice that only the note property” to be more concise and avoid ambiguous language
## Testing the application
- [x] Typo: Change “can be done using” to “can be done by using”
- [x] Change “You’ll write tests using JUnit” to “You can write tests by using JUnit” to avoid future tense and fix a typo.
- [x] Typo: Change “query using” to “query by using”
- [x] Change “It will try” to “It tries” to avoid future tense.
- [x] Typo: Change “query using” to “query by using”

**Comment by AustinSeto** [comment]
Hi @Rwalls1 I've addressed some of your changes in the linked pull request #22 

The comments regarding the paragraphs on dev mode are actually imported from https://github.com/OpenLiberty/guides-common, I can make the change there but it would affect all the guides using dev mode. 

Regarding the comments on the sentences with future tense such as "you'll implement...", maybe instead a rewording might make more sense? For example, currently the guide contains:

> You’ll create three object types to define the structure of the data returned by GraphQL. You’ll apply various annotations to the properties and declaration of a Java class to define an object type.

What do you think if instead we reworded it to:

> Object types define the structure of the data returned by GraphQL. Annotations applied to the declaration and properties of Java classes define object types.

**Comment by Rwalls1** [comment]
@AustinSeto In that case, the dev mode suggestion can be ignored. I think your suggested revision to that paragraph sounds good. Also, I added some comments to the [PR](https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/22#pullrequestreview-595766310).
