### ISSUE TITLE
Dev content review for rework-3

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-graphql#30]
1. **What you’ll learn**
- [x] suggest the diagram as https://github.ibm.com/websphere/openliberty-guides-team/blob/main/guides-resources/guide-microprofile-graphql.pptx
- [x] suggest to change

> The guide application includes GraphiQL. GraphiQL helps you make POST requests to a GraphQL service. In GraphiQL, you need to type only the body of the request for the purposes of manual tests and examples.

to

> The guide application includes an interactive GraphQL tool (GraphiQL). GraphiQL helps you make queries to a GraphQL service. In GraphiQL pane, you need to type only the body of the query in json format for the purposes of manual tests and examples.

- [x] Remove the paragraph "For an example of accessing GraphQL using another service,..."

---

2. **Creating GraphQL object types**
- [x] Instead of create SystemLoad and SystemLoadData, let say they are provided, and explain a bit what data they are.
- [x] move mvn -pl models install instuction to the Building and running the application section

---

3. Based on the design, 
- [x] there should be a  **Implementing System service** section.

---

4. **Implementing GraphQL resolvers**
- [x] Should talk about java() and operatingSystem() instead of getSystemLoad().

---

5. Add **Building and running the application** section for mvn, docker, and startContainers.sh 

---

6. **Querying the GraphQL service**  
- [x] suggest rename to **Running GraphQL queries**
- [x] for query the note, tell users no need to run a full query

---

7. - [x] Save the code for inventory in somewhere. Remove it from this guide.

**Comment by AustinSeto** [comment]
Moved `inventory` code out of the intro guide code to new draft guide repo at https://github.com/OpenLiberty/draft-guide-graphql-client

**Comment by AustinSeto** [comment]
Updated lgdev site with the changes requested here. Changes are in this PR: https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/29

**Comment by gkwan-ibm** [comment]
- [x]  suggest to update the diagram as https://github.ibm.com/websphere/openliberty-guides-team/blob/main/guides-resources/guide-microprofile-graphql.pptx
    - align the REST apis and queries
    - the png file should have more empty spaces, so that the diagram won't show too big
 ---
 **Creating GraphQL object types**
- [x] suggest in the "To save time, ..." paragraph
   - "The `SystemLoad` class maps to the` systemLoad` object type, ..."  statement
      - remove hotspot for `SystemLoad` because did in the first statement. Instead, add hotspot to `systemLoad` object type
    - "The `SystemLoadData` class maps to the `loadData` object type. " statement
       - remove hotspot for `SystemLoadData` because did in the first statement. Instead, add hotspot to `loadData` object type
 - [x] in the "The `@Name` annotation maps...", suggest to remove hotspots for the second and third `@Name`.
---
**Implementing GraphQL resolvers**
- [x] Should the "The `@Name` appears again here...." paragraph be above the "The other query request..." because the `@Name` paragraph is for the first query?

**Comment by AustinSeto** [comment]
Made all changes and updated lgdev site

**Comment by gkwan-ibm** [comment]
- [x] suggest to improve the diagram as https://github.ibm.com/websphere/openliberty-guides-team/blob/main/guides-resources/guide-microprofile-graphql.pptx
  -  3 system boxes instead of 2
  - make the graphql box wider to line up with the system boxes
  - align the @ apis left instead of center
  - make sure the diagram look symmetric
