### ISSUE TITLE
Wrong port number

### ISSUE THREAD

**Issue by priyyanshi** [OpenLiberty/guide-microprofile-graphql#31]
In the `Running GraphQL queries` section of the guide, the URLs use port number `9080` but in the `startContainers.sh` script the containers are started on port `9082`. These URLS need to corrected to use port `9082` or the script needs to be updated to start containers on port `9080`.

**Comment by AustinSeto** [comment]
Addressed by changing port number in instructions. See commit https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/29/commits/0ce5742862099281c2350c7a3ec5d26fc1d57649 added to https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/29. Let me know if there are any other issues accessing the application.
