### ISSUE TITLE
User content review 1

### ISSUE THREAD

**Issue by davidwyao** [OpenLiberty/guide-microprofile-graphql#38]
### Time to completion
- 35 minutes
### Clarity of steps
Creating GraphQL object types
- Add brief explanation of reasoning for non-nullable properties

Implementing GraphQL resolvers
- Add brief explanation of difference between GET and query
### Logic Errors
N/A
### Not working
N/A
### Usability issues
Building and running the application:
- Visual separation between the three docker commands, or clarify they can be run at once
### Basic understanding
Topic is well explained. Useful examples of numerous annotations, class structure, and querying.

**Comment by gkwan-ibm** [comment]
suggest to change the time to 30 min
