### ISSUE TITLE
User Review 2

### ISSUE THREAD

**Issue by Kevcpro** [OpenLiberty/guide-microprofile-graphql#39]
Time:  25 minutes

Clarity of Steps:
-  Easy to follow throughout the whole tutorial. It was clear what needs to be done in each step.

Logic Errors: N/A

Not Working: N/A

Usability Issues: N/A

Basic Understanding:

- I found that the explanation for GraphQL was very thorough. The examples made a lot of sense and it made it easy to understand what was being done in each step.

**Comment by gkwan-ibm** [comment]
close
- nothing to address
